<div align="center">

**LAPORAN PRAKTIKUM**

**STRUKTUR DATA**

**“Tipe Data dan Variabel”**

**Disusun Oleh :**

**M. Yiwanu Marhudan**

**2611533003**

**Dosen Pengampu:**

**Wahyudi.DR.. S.T.M.T**

**Asisten Praktikum:**

**Sherly Sukmadira**

<br>

 <img src="images/logo_unand.png" width="200">

<br>

**FAKULTAS TEKNOLOGI INFORMASI**

**DEPARTEMEN INFORMATIKA**

**UNIVERSITAS ANDALAS**

**2026**

</div>

## KATA PENGANTAR

Puji beserta syukur saya panjatkan atas kehadirat Tuhan Yang Maha Esa yang telah memberikan rahmat dan berkatnya, sehingga saya dapat menyelesaikan laporan praktikum mengenai pengenalan tipe data dan variabel Python yang telah dilaksanakan sebagai pertemuan ke-2 untuk mata kuliah Praktikum Algoritma dan Pemrograman. Praktikum ini berfokus pada pembahasan jenis - jenis tipe data yang ada pada bahasa pemrograman Python.

Melalui praktikum ini, hasil yang diharapkan adalah saya dapat memahami secara langsung konsep mengenai macam - macam tipe data Python dan bisa mengindentifikasi nilai dari suatu variabel serta bisa mengelompokkan nilai variabel berdasarkan tipe datanya pada bahasa pemrograman Python.

Saya menyadari bahwa laporan praktikum ini masih memiliki banyak kekurangan. Oleh karena itu, kritik dan saran yang membangun sangat diharapkan demi perbaikan dan pengembangan di masa mendatang.

Padang, 2026

---
# BAB I
# PENDAHULUAN

## 1.1 Latar Belakang
Perkembangan teknologi informasi yang semakin pesat meningkatkan kebutuhan terhadap pengolahan data dan sistem otomatis yang cepat serta efisien. Salah satu bahasa pemrograman yang banyak digunakan saat ini adalah Python. Python memiliki sintaks yang sederhana dan mudah dipahami, serta dapat diterapkan dalam berbagai bidang seperti pengembangan aplikasi, analisis data, dan kecerdasan buatan. Oleh karena itu, pemahaman mengenai dasar-dasar pemrograman Python menjadi hal penting dalam proses pembuatan program.

Salah satu konsep dasar tersebut adalah variabel. Variabel digunakan untuk menyimpan suatu nilai yang dapat dipanggil dan diolah kembali selama program berjalan. Penggunaan variabel membuat pengelolaan data menjadi lebih mudah dan fleksibel.

Selain variabel, tipe data juga perlu dipahami karena menentukan karakteristik suatu nilai dan operasi yang dapat dilakukan. Beberapa tipe data dasar dalam Python yaitu `int`, `float`, `str`, dan `bool`. Python menggunakan sistem dynamic typing, sehingga tipe data akan ditentukan secara otomatis berdasarkan nilai yang diberikan kepada variabel.

Pemahaman mengenai variabel dan tipe data menjadi dasar sebelum mempelajari konsep pemrograman yang lebih lanjut. Oleh karena itu, praktikum ini dilakukan untuk memberikan pemahaman kepada praktikan mengenai penggunaan variabel, pengenalan tipe data dasar, serta penerapannya dalam program Python.


## 1.2 Tujuan
1. Memahami Konsep Dasar Variabel.
2. Mengenali Jenis Tipe Data Variabel.
3. Mengimplementasikan Deklarasi dan Konversi Tipe Data.
4. Menganalisis dan Mengatasi Galat (Error).

## 1.3 Manfaat
1. Penguasaan Fondasi Pemrograman
2. Peningkatan Keterampilan Praktis (Hands-On)
3. Pencegahan Kesalahan Logika Kode

---
# BAB II
# PEMBAHASAN

## 2.1 Landasan Teori

**1. Pengenalan Bahasa Pemrograman Python**

​Python merupakan bahasa pemrograman tingkat tinggi (_high-level language_) yang bersifat _interpreted_, _object-oriented_, dan _dynamically typed_. Diciptakan oleh Guido van Rossum pada tahun 1991, Python dirancang dengan penekanan pada keterbacaan kode (_code readability_) melalui penggunaan indentasi yang bersih. Sintaksisnya yang intuitif membuat Python banyak digunakan dalam berbagai bidang, mulai dari pengembangan perangkat lunak, otomatisasi sistem, hingga analisis data dan kecerdasan buatan.

​**2. Konsep Variabel dalam Python**

​Variabel merupakan nama atau label berpenunjuk (_identifier_) yang terikat pada suatu lokasi di memori komputer untuk menyimpan nilai tertentu. Dalam Python, variabel tidak perlu dideklarasikan secara eksplisit beserta tipe datanya sebelum digunakan; variabel dibuat secara otomatis saat suatu nilai dialokasikan padanya menggunakan operator penugasan (`=`). Penulisan nama variabel di Python harus mengikuti aturan tertentu, seperti bersifat case-sensitive, tidak boleh diawali oleh angka, dan tidak boleh menggunakan kata kunci (_keywords_) bawaan sistem.

**​3. Tipe Data Dasar (Primitive Data Types)**

​Tipe data mengklasifikasikan jenis nilai yang dimiliki oleh suatu variabel sehingga sistem mengetahui cara mengolah dan menyimpan data tersebut di memori. Python memiliki beberapa tipe data dasar yang sering digunakan:

> * ​Integer (`int`): Tipe data berupa bilangan bulat, baik positif maupun negatif, tanpa komponen desimal (contoh: `-5`, `0`, `100`).

> * ​Floating-Point (`float`): Tipe data berupa angka yang memiliki titik desimal atau pecahan (contoh: `3.14`, `-0.01`).

> * ​String (`str`): Tipe data berupa urutan karakter/teks yang diapit oleh tanda petik tunggal (`'...'`) atau ganda (`"..."`) (contoh: `"Praktikum Python"`).

> * ​Boolean (`bool`): Tipe data logika yang hanya memiliki dua nilai kebenaran, yaitu `True` (benar) dan `False` (salah).

**​4. Dynamic Typing dan Type Casting**

​Python menganut sistem _dynamic typing_, yang berarti tipe data dari suatu variabel ditentukan secara otomatis pada saat program berjalan (_runtime_) berdasarkan nilai yang dimasukkan, bukan saat variabel dideklarasikan. Selain itu, Python mendukung konversi tipe data atau _type casting_, yaitu proses mengubah nilai dari satu tipe data ke tipe data lainnya secara eksplisit (seperti menggunakan fungsi `int()`, `float()`, atau `str()`) maupun implisit oleh interpreter. Pemahaman terhadap type casting sangat penting untuk menghindari kesalahan tipe data (_type error_) saat melakukan operasi aritmetika atau manipulasi string.# BAB II

## 2.2 Kode Program

### 2.2.1 Program "Boolean_2611533003"

In [1]:
#Nama variabel ditambah 4 digit nim terakhir contoh: nama_1234
# Deklarasi variabel dengan tipe data boolean
is_lulus_3003 = True
is_cumlaide_3003 = False

# Menggukan Boolean
nilai_3003 = 85
batas_lulus_3003 = 75

# Menentukan nilai Boolean dari kondisi
status_kelulusan_3003 = nilai_3003 >= batas_lulus_3003

print("=== Check Kelulusan ===")
print("Nilai:", nilai_3003)
print("Apakah lulus:", status_kelulusan_3003)

=== Check Kelulusan ===
Nilai: 85
Apakah lulus: True


**Penjelasan :**
1. Bagian 1 sampai 2 berfungsi untuk membuat variabel Boolean is_lulus_3003 dengan nilai True dan is_cumlaide_3003 dengan nilai False.
2. Bagian 3 sampai 4 berfungsi untuk menyimpan nilai mahasiswa dan batas nilai kelulusan ke dalam variabel.
3. Bagian 3 sampai 4 berfungsi untuk menyimpan nilai mahasiswa dan batas nilai kelulusan ke dalam variabel.
4. Bagian 6 sampai 8 berfungsi untuk menampilkan judul, nilai mahasiswa, dan hasil status kelulusan ke layar.

### 2.2.2 Program "Input_2611533003"

In [2]:
# Buat program untuk menghitung luas persegi panjang
# Nama variabel ditambah 4 digit nim terakhir contoh: nama_1234
# Program ini menggunakan fungsi input() untuk meminta pengguna
# Memasukkan nilai panjang dan lebar persegi panjang
# Nilai yang dimasukkan akan dikonversi menjadi tipe data integer
panjang_3003 = input("Masukkan panjang: ")
lebar_3003 = input("Masukkan lebar: ")
luas_3003 = int(panjang_3003) * int(lebar_3003)
print("Luas persegi panjang adalah:", luas_3003)

Masukkan panjang: 10
Masukkan lebar: 5
Luas persegi panjang adalah: 50


**Penjelasan :**
1. Bagian 1 sampai 2 berfungsi untuk meminta pengguna memasukkan nilai panjang dan lebar persegi panjang menggunakan fungsi input().
2. Bagian 3 berfungsi untuk mengubah nilai panjang dan lebar menjadi tipe data integer, kemudian menghitung luas persegi panjang.
3. Bagian 4 berfungsi untuk menampilkan hasil perhitungan luas persegi panjang ke layar.

### 2.2.3 Program "Konstanta_2611533003"

In [3]:
from typing import Final
PI: Final = 3.14
print(" %f" % (PI))
jari_3003 = float(input("Masukkan jari-jari lingkaran: "))
luas_3003 = PI * jari_3003 * jari_3003
print("Luas lingkaran dengan jari-jari %.2f adalah %.2f" % (jari_3003, luas_3003))

 3.140000
Masukkan jari-jari lingkaran: 10
Luas lingkaran dengan jari-jari 10.00 adalah 314.00


**Penjelasan :**
1. Bagian 1 sampai 2 berfungsi untuk mengimpor Final dan menentukan nilai konstanta PI sebesar 3.14.
2. Bagian 3 sampai 4 berfungsi untuk menampilkan nilai PI dan meminta pengguna memasukkan nilai jari-jari lingkaran.
3. Bagian 5 berfungsi untuk menghitung luas lingkaran menggunakan nilai PI dan jari-jari yang telah dimasukkan.
4. Bagian 6 berfungsi untuk menampilkan hasil perhitungan luas lingkaran dengan format dua angka di belakang koma.

### 2.2.4 Program "Numerik_2611533003"

In [4]:
#create a variabel with integer value.
a_3003=100
print("The type of variable having value",a_3003,"is",type(a_3003))

#create a variable with float value.
b_3003=10.2345
print("The type of variable having value",b_3003,"is",type(b_3003))

#create a variable with complex value
c_3003=100+3j
print("The type of variable having value",c_3003,"is",type(c_3003))

The type of variable having value 100 is <class 'int'>
The type of variable having value 10.2345 is <class 'float'>
The type of variable having value (100+3j) is <class 'complex'>


**Penjelasan :**
1. Bagian 1 sampai 2 berfungsi untuk membuat variabel a_3003 dengan nilai 100 dan menampilkan nilai serta tipe datanya menggunakan fungsi type().
2. Bagian 3 sampai 4 berfungsi untuk membuat variabel b_3003 dengan nilai 10.2345 dan menampilkan nilai serta tipe datanya.
3. Bagian 5 sampai 6 berfungsi untuk membuat variabel c_3003 dengan nilai kompleks 100+3j dan menampilkan nilai serta tipe datanya.

### 2.2.5 Program "String_2611533003"

In [5]:
#nama variabel ditambah 4 digit nim terakhir contoh: nama_1234
#ganti programnya dan data masing2
nama_3003 = "M. Yiwanu Marhudan_3003"
jenis_kelamin_3003 = 'L'
alamat_3003 = """
    pesisir selatan
    kec.silaut
    silaut 1
"""
agama_3003 = 'islam'
print("nama saya adalah: ", nama_3003)
print("Jenis kelamin saya adalah: ", jenis_kelamin_3003)
print("Alamat saya adalah: ", alamat_3003)
print("Agama saya adalah: ", agama_3003)

nama saya adalah:  M. Yiwanu Marhudan_3003
Jenis kelamin saya adalah:  L
Alamat saya adalah:  
    pesisir selatan
    kec.silaut
    silaut 1

Agama saya adalah:  islam


**Penjelasan :**
1. Bagian 1 sampai 2 berfungsi untuk membuat variabel nama_3003 dan jenis_kelamin_3003 yang menyimpan data nama dan jenis kelamin.
2. Bagian 3 sampai 7 berfungsi untuk membuat variabel alamat_3003 yang menyimpan data alamat dalam bentuk string yang terdiri dari beberapa baris.
3. Bagian 8 berfungsi untuk membuat variabel agama_3003 yang menyimpan data agama.
4. Bagian 9 sampai 12 berfungsi untuk menampilkan nama, jenis kelamin, alamat, dan agama ke layar menggunakan fungsi print().

---
# BAB III
# KESIMPULAN

Berdasarkan kegiatan praktikum Algoritma dan Pemrograman yang telah dilakukan, dapat diperoleh beberapa kesimpulan sebagai berikut:

**1. Bahasa Pemrograman Python:** Python merupakan bahasa pemrograman yang fleksibel dengan sintaks yang sederhana dan mudah dipelajari. Hal tersebut membuat Python sesuai digunakan untuk memahami konsep dasar pemrograman serta membangun berbagai jenis program.

**2. Lingkungan Pengembangan:** Penggunaan aplikasi seperti VS Code dan Google Colab dapat mempermudah proses pembuatan dan pengujian program. Kedua lingkungan tersebut membantu programmer dalam menulis, menjalankan, serta memperbaiki kode dengan lebih praktis.

**3. Pengelolaan Kode dengan GitHub:** Git dan GitHub dapat digunakan untuk menyimpan serta mengelola kode program secara terorganisir. Perintah seperti `git init`, `add`, `commit`, dan `push` membantu proses pencadangan dan pengelolaan perubahan kode sehingga pekerjaan dapat dilakukan dengan lebih terstruktur.


---
## DAFTAR PUSTAKA

[1]  ​Lubanovic, B. (2019). Introducing Python: Modern Computing in Simple Packages (2nd ed.). O'Reilly Media. Link: https://www.oreilly.com/library/view/introducing-python-2nd/9781492051374/

[2] ​Matthes, E. (2019). Python Crash Course: A Hands-On, Project-Based Introduction to Programming (2nd ed.). No Starch Press. Link: https://nostarch.com/pythoncrashcourse2e

[3] ​Severance, C. R. (2016). Python for Everybody: Exploring Data in Python 3. CreateSpace Independent Publishing Platform. Link: https://www.py4e.com/book

[4] ​Swaroop, C. H. (2013). A Byte of Python. Link: https://python.swaroopch.com/