<div align="center">

**LAPORAN PRAKTIKUM**

**STRUKTUR DATA**

**“Pengenalan python, vscode, dan koneksi ke github”**

**Disusun Oleh :**

**M. Yiwanu Marhudan**

**2611533003**

**Dosen Pengampu:**

**Wahyudi.DR.. S.T.M.T**

**Asisten Praktikum:**

**Sherly Sukmadira**

<br>

 <img src="images/logo_unand.png" width="200">

<br>

**FAKULTAS TEKNOLOGI INFORMASI**

**DEPARTEMEN INFORMATIKA**

**UNIVERSITAS ANDALAS**

**2026**

</div>

## KATA PENGANTAR

Puji syukur penulis panjatkan atas kehadirat Tuhan Yang Maha Esa yang telah memberikan rahmat dan berkatnya, sehingga penulis dapat menyelesaikan laporan praktikum “Pengenalan Python, VSCode, dan Koneksi ke GitHub” yang telah dilaksanakan sebagai pertemuan ke-1 untuk mata kuliah Praktikum Struktur Data. Praktikum ini berfokus pada pembahasan pengenalan Python, penggunaan Visual Studio Code (VSCode), serta koneksi dan penggunaan GitHub.

Melalui praktikum ini, hasil yang diharapkan adalah penulis dapat memahami dan mengimplementasikan secara langsung konsep dasar penggunaan Python, VSCode, dan koneksi ke GitHub pada real project.

Penulis menyadari bahwa laporan praktikum ini masih memiliki banyak kekurangan. Oleh karena itu, kritik dan saran yang membangun sangat diharapkan demi perbaikan dan pengembangan di masa mendatang.

Padang, 2026

---
# BAB I
# PENDAHULUAN

## 1.1 Latar Belakang
Perkembangan teknologi dalam bidang pemrograman membuat pemahaman terhadap bahasa pemrograman dan perangkat pendukungnya menjadi hal yang penting bagi mahasiswa Informatika. Python merupakan salah satu bahasa pemrograman yang dapat digunakan untuk mempelajari dasar-dasar pemrograman. Selain bahasa pemrograman, diperlukan juga perangkat pengembangan seperti Visual Studio Code (VSCode) serta platform GitHub untuk membantu proses pengembangan dan pengelolaan program.

Oleh karena itu, praktikum ini dilakukan untuk mengenalkan Python, VSCode, serta koneksi ke GitHub sebagai dasar dalam melakukan pengembangan program dan pengelolaan proyek.

## 1.2 Tujuan
1. Mengenal dasar penggunaan bahasa pemrograman Python.
2. Mengenal dan menggunakan Visual Studio Code (VSCode) sebagai lingkungan pengembangan program.
3. Memahami cara menghubungkan proyek dengan GitHub.

## 1.3 Manfaat
1. Menambah pemahaman mengenai penggunaan Python dalam pemrograman.
2. Meningkatkan kemampuan dalam menggunakan VSCode untuk membuat dan mengelola program.
3. Mengetahui dasar penggunaan GitHub untuk menyimpan dan mengelola proyek pemrograman.

---
# BAB II
# PEMBAHASAN

## 2.1 Dasar Teori

1. Python merupakan bahasa pemrograman tingkat tinggi yang memiliki sintaks sederhana dan mudah dipahami. Python dapat digunakan untuk membuat berbagai jenis program dan banyak digunakan dalam pembelajaran pemrograman.
2. Visual Studio Code merupakan code editor yang digunakan untuk menulis, mengedit, dan menjalankan program. VSCode mendukung berbagai bahasa pemrograman, termasuk Python, serta menyediakan berbagai fitur yang membantu proses pengembangan program.
3. GitHub merupakan platform yang digunakan untuk menyimpan dan mengelola kode program secara daring. GitHub juga dapat digunakan untuk melakukan kolaborasi dan menyimpan riwayat perubahan pada suatu proyek.
4. Koneksi VSCode dengan GitHub memungkinkan proyek yang dibuat melalui VSCode untuk dihubungkan dengan repository GitHub sehingga kode dapat disimpan dan dikelola secara daring.

## 2.2 Kode Program

### 2.2.1 Program "A_2611533003"
Jalankan sel kode di bawah ini agar Jupyter otomatis menyimpan kodenya beserta outputnya sebagai satu kesatuan (tidak perlu screenshot terpisah untuk hasil run).

In [ ]:
# Program pertama
"""
komentar
dua baris atau lebih
pertemuan 1 praktikum alpro
"""

print("hello world")
print()
print("print ini menghasilkan")
print("empat baris output")
print("/ \\\\ / \\\\ / \\\\ / \\\\ / ")
print("program ini" + "dibuat oleh a\n" + "M. Yiwanu Marhudan 2611533003")

hello world

print ini menghasilkan
empat baris output
/ \\ / \\ / \\ / \\ / 
program inidibuat oleh a
M. Yiwanu Marhudan 2611533003


**Penjelasan :**
1. Bagian pertama sampai keenam sebagai penjelas sebuah struktur program
2. Bagian ketujuh sampai terakhir menghasilkan output
3. Program ini dijalankan dengan bahasa Python

### 2.2.2 Program "Boolean_2611533003"

In [1]:
#Nama variabel ditambah 4 digit nim terakhir contoh: nama_1234
# Deklarasi variabel dengan tipe data boolean
is_lulus_3003 = True
is_cumlaide_3003 = False

# Menggukan Boolean
nilai_3003 = 85
batas_lulus_3003 = 75

# Menentukan nilai Boolean dari kondisi
status_kelulusan_3003 = nilai_3003 >= batas_lulus_3003

print("=== Check Kelulusan ===")
print("Nilai:", nilai_3003)
print("Apakah lulus:", status_kelulusan_3003)

=== Check Kelulusan ===
Nilai: 85
Apakah lulus: True


**Penjelasan :**
1. Bagian 1 sampai 2 berfungsi untuk membuat variabel Boolean is_lulus_3003 dengan nilai True dan is_cumlaide_3003 dengan nilai False.
2. Bagian 3 sampai 4 berfungsi untuk menyimpan nilai mahasiswa dan batas nilai kelulusan ke dalam variabel.
3. Bagian 3 sampai 4 berfungsi untuk menyimpan nilai mahasiswa dan batas nilai kelulusan ke dalam variabel.
4. Bagian 6 sampai 8 berfungsi untuk menampilkan judul, nilai mahasiswa, dan hasil status kelulusan ke layar.

### 2.2.3 Program "Input_2611533003"

In [2]:
# Buat program untuk menghitung luas persegi panjang
# Nama variabel ditambah 4 digit nim terakhir contoh: nama_1234
# Program ini menggunakan fungsi input() untuk meminta pengguna
# Memasukkan nilai panjang dan lebar persegi panjang
# Nilai yang dimasukkan akan dikonversi menjadi tipe data integer
panjang_3003 = input("Masukkan panjang: ")
lebar_3003 = input("Masukkan lebar: ")
luas_3003 = int(panjang_3003) * int(lebar_3003)
print("Luas persegi panjang adalah:", luas_3003)

Masukkan panjang: 10
Masukkan lebar: 5
Luas persegi panjang adalah: 50


**Penjelasan :**
1. Bagian 1 sampai 2 berfungsi untuk meminta pengguna memasukkan nilai panjang dan lebar persegi panjang menggunakan fungsi input().
2. Bagian 3 berfungsi untuk mengubah nilai panjang dan lebar menjadi tipe data integer, kemudian menghitung luas persegi panjang.
3. Bagian 4 berfungsi untuk menampilkan hasil perhitungan luas persegi panjang ke layar.

### 2.2.4 Program "Konstanta_2611533003"

In [3]:
from typing import Final
PI: Final = 3.14
print(" %f" % (PI))
jari_3003 = float(input("Masukkan jari-jari lingkaran: "))
luas_3003 = PI * jari_3003 * jari_3003
print("Luas lingkaran dengan jari-jari %.2f adalah %.2f" % (jari_3003, luas_3003))

 3.140000
Masukkan jari-jari lingkaran: 10
Luas lingkaran dengan jari-jari 10.00 adalah 314.00


**Penjelasan :**
1. Bagian 1 sampai 2 berfungsi untuk mengimpor Final dan menentukan nilai konstanta PI sebesar 3.14.
2. Bagian 3 sampai 4 berfungsi untuk menampilkan nilai PI dan meminta pengguna memasukkan nilai jari-jari lingkaran.
3. Bagian 5 berfungsi untuk menghitung luas lingkaran menggunakan nilai PI dan jari-jari yang telah dimasukkan.
4. Bagian 6 berfungsi untuk menampilkan hasil perhitungan luas lingkaran dengan format dua angka di belakang koma.

### 2.2.5 Program "Numerik_2611533003"

In [4]:
#create a variabel with integer value.
a_3003=100
print("The type of variable having value",a_3003,"is",type(a_3003))

#create a variable with float value.
b_3003=10.2345
print("The type of variable having value",b_3003,"is",type(b_3003))

#create a variable with complex value
c_3003=100+3j
print("The type of variable having value",c_3003,"is",type(c_3003))

The type of variable having value 100 is <class 'int'>
The type of variable having value 10.2345 is <class 'float'>
The type of variable having value (100+3j) is <class 'complex'>


**Penjelasan :**
1. Bagian 1 sampai 2 berfungsi untuk membuat variabel a_3003 dengan nilai 100 dan menampilkan nilai serta tipe datanya menggunakan fungsi type().
2. Bagian 3 sampai 4 berfungsi untuk membuat variabel b_3003 dengan nilai 10.2345 dan menampilkan nilai serta tipe datanya.
3. Bagian 5 sampai 6 berfungsi untuk membuat variabel c_3003 dengan nilai kompleks 100+3j dan menampilkan nilai serta tipe datanya.

### 2.2.6 Program "String_2611533003"

In [5]:
#nama variabel ditambah 4 digit nim terakhir contoh: nama_1234
#ganti programnya dan data masing2
nama_3003 = "M. Yiwanu Marhudan_3003"
jenis_kelamin_3003 = 'L'
alamat_3003 = """
    pesisir selatan
    kec.silaut
    silaut 1
"""
agama_3003 = 'islam'
print("nama saya adalah: ", nama_3003)
print("Jenis kelamin saya adalah: ", jenis_kelamin_3003)
print("Alamat saya adalah: ", alamat_3003)
print("Agama saya adalah: ", agama_3003)

nama saya adalah:  M. Yiwanu Marhudan_3003
Jenis kelamin saya adalah:  L
Alamat saya adalah:  
    pesisir selatan
    kec.silaut
    silaut 1

Agama saya adalah:  islam


**Penjelasan :**
1. Bagian 1 sampai 2 berfungsi untuk membuat variabel nama_3003 dan jenis_kelamin_3003 yang menyimpan data nama dan jenis kelamin.
2. Bagian 3 sampai 7 berfungsi untuk membuat variabel alamat_3003 yang menyimpan data alamat dalam bentuk string yang terdiri dari beberapa baris.
3. Bagian 8 berfungsi untuk membuat variabel agama_3003 yang menyimpan data agama.
4. Bagian 9 sampai 12 berfungsi untuk menampilkan nama, jenis kelamin, alamat, dan agama ke layar menggunakan fungsi print().

---
## Tugas Praktikum

**Soal : Membuat sebuah file program Python bebas dengan nama tugas1_nim.py.**


**Kode Jawaban :**

a. Kode Program "Alpro_A_2611533003"

In [ ]:
print("=== BIODATA MAHASISWA ===")
print("Nama    : M. Yiwanu Marhudan")
print("NIM     : 2611533003")
print("Jurusan : Informatika")
print("Kelas   : IF-A")
print("Hobi    : Membaca Komik")
print()
print()
print()
print("       *")
print("      ***")
print("     *****")
print("    *******")
print("   *********")
print("  ***********")
print(" *************")
print("      ||")
print("      ||")
print("      ||")
print("     ||||")

**Output :**

**Penjelasan :** Program Tugas 1 digunakan untuk menampilkan biodata mahasiswa dan membuat pola sederhana menggunakan karakter * dan |. Perintah print() digunakan untuk menampilkan biodata seperti nama, NIM, jurusan, kelas, dan hobi. Perintah print() kosong digunakan untuk memberikan jarak antara biodata dengan pola. Karakter * disusun secara bertahap sehingga membentuk pola, sedangkan karakter | digunakan sebagai bagian bawah pola.

---
# BAB III
# KESIMPULAN

Berdasarkan praktikum yang telah dilakukan, dapat disimpulkan bahwa Python merupakan bahasa pemrograman yang dapat digunakan untuk membuat dan menjalankan program dengan sintaks yang sederhana. Visual Studio Code dapat digunakan sebagai lingkungan untuk menulis dan menjalankan kode Python, sedangkan GitHub dapat digunakan untuk menyimpan dan mengelola proyek secara daring.

Dalam praktikum ini, penulis mempelajari dasar penggunaan Python, VSCode, serta koneksi ke GitHub. Dengan memahami ketiga hal tersebut, proses pembuatan, pengelolaan, dan penyimpanan program dapat dilakukan dengan lebih terstruktur.

---
## DAFTAR PUSTAKA

[1] Python Software Foundation, "Python Documentation," Python, [Online]. Tersedia: https://docs.python.org/3/. [Diakses 6 September 2026].

[2] Microsoft, "Visual Studio Code Documentation," Visual Studio Code, [Online]. Tersedia: https://code.visualstudio.com/docs. [Diakses 6 September 2026].

[3] GitHub, "GitHub Documentation," GitHub, [Online]. Tersedia: https://docs.github.com/. [Diakses 6 September 2026].